### ISSUE TITLE
Do not move out local scope imports

### ISSUE THREAD

**Issue by timothyklim** [NeQuissimus/sort-imports#1]
Hi! Thank you for this great plugin!
This is a first issue 😃 

Expected:

```scala
object DC {
  def config(dcId: Int, settings: Settings): Config = {
    import settings.dc
    // ...
```

Current result:

```scala
import settings.dc
object DC {
  def config(dcId: Int, settings: Settings): Config = {
    // ...
```

**Comment by NeQuissimus** [comment]
Hey, thanks :)

yeah, local imports and import order that changes identifier shadowing are currently broken.
(and the code is a hot mess altogether :D)
