### ISSUE TITLE
Support regex in group definition

### ISSUE THREAD

**Issue by jozic** [NeQuissimus/sort-imports#16]
It seems I can't combine several packages in a group, like (java + javax).
`Scalastyle` allows for that using regex. One can say "javax?" and have those in same group.
I think that's easy to implement, but it will be not backward compatible with current config file.
If that's okay, i can send a PR at some point, if not, feel free to close this issue.
Thanks!

**Comment by NeQuissimus** [comment]
I like it. I don't think it should break much. Go for it!

**Comment by slandelle** [comment]
Should be closed as of #55 released in 0.5.0.

**Comment by jozic** [comment]
indeed, thanks @slandelle
