### ISSUE TITLE
import shadowing not been taken into account

### ISSUE THREAD

**Issue by He-Pin** [NeQuissimus/sort-imports#38]
```scala
  import StageActorRefSpec._
  import ControlProtocol._
```
gives
```scala
  import ControlProtocol._
  import StageActorRefSpec._
```
so I have change it into 

```
  import StageActorRefSpec.ControlProtocol._
  import StageActorRefSpec._
```

**Comment by NeQuissimus** [comment]
Yeah, the README states that. It is a more complex problem than just sorting text lines :D

**Comment by NeQuissimus** [comment]
I am going to close this. I believe that we cannot solve this issue without becoming a semantic rule.
If you would like such a rule, please consider https://github.com/liancheng/scalafix-organize-imports/

I envision `sort-imports` to stay a syntactic rule for simple use cases, so it can run as quickly as possible.
