### ISSUE TITLE
Support symbol first import sort order

### ISSUE THREAD

**Issue by slandelle** [NeQuissimus/sort-imports#47]
Thanks a lot for this plugin, this is something we were really missing!

Then, it looks like sort is purely alphabetical and doesn't account for packages.

```scala
// currently
import foo.bar._
import foo._

// expecting
import foo._
import foo.bar._
```

or

```scala
// currently
import foo.bar.Baz
import foo.{ Xxx, Yyy}

// expecting
import foo.{ Xxx, Yyy}
import foo.bar.Baz
```

**Comment by NeQuissimus** [comment]
Yeah, this is one of the things we currently don't account for. SortImports is indeed quite dumb and just sorts alphabetically :)
Is (currently) has no concept of what the code actually does and just looks at each line as plain text.

If you would like to contribute, you are more than welcome to give it it a shot. Add the above as tests and see if you can make the code sort the imports properly :)

**Comment by slandelle** [comment]
We'll try to contribute a fix.

Basically, ASCII sort order is the standard in the Java world (from [Google's style guide](https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing)).

However, this works well in Java where the wildcard is `*` that comes in the ASCII table before alphanums. In Scala, the wildcard is `_` and Scala has grouped imports.

A not-perfect-quick-and-win solution would be to always have `_` and `{` come before alphanums, whatever the position in the import.

@NeQuissimus Would you be fine with this?

**Comment by NeQuissimus** [comment]
Yes but I would love for that to be behind a flag/configuration option. Maybe `asciiSort = true` as the default and if you switch it to `false`, it uses your above logic?
What do you think?

**Comment by slandelle** [comment]
Makes sense
