### ISSUE TITLE
"scala" block includes scalafix packages

### ISSUE THREAD

**Issue by etspaceman** [NeQuissimus/sort-imports#6]
Hey there. Great plugin!

Was playing around with it today and noticed that, when applied to one of my SBT plugins (which sets some `scalafix` settings), the `scalafix` packages were considered as a part of the `scala` block.

```
import io.gatling.sbt.GatlingKeys._
import io.gatling.sbt.GatlingPlugin
import org.scalafmt.sbt.ScalafmtPlugin
import sbt.Keys._
import sbt._
import scalafix.sbt.ScalafixPlugin
import scalafix.sbt.ScalafixPlugin.autoImport._
```

Becomes

```
import scalafix.sbt.ScalafixPlugin
import scalafix.sbt.ScalafixPlugin.autoImport._

import io.gatling.sbt.GatlingKeys._
import io.gatling.sbt.GatlingPlugin
import org.scalafmt.sbt.ScalafmtPlugin
import sbt.Keys._
import sbt._
```

With a configuration like so:

```
SortImports.blocks = [
  "java",
  "scala",
  "*"
]
```

**Comment by pjrt** [comment]
It also includes things like `scalaz`.

**Comment by mwz** [comment]
Using the following config fixed this for me:
```
SortImports.blocks = [
  "java.",
  "scala.",
  "*"
]
```

**Comment by pjrt** [comment]
Ah! Nice work around @mwz !

**Comment by pjrt** [comment]
@NeQuissimus maybe update the README with @mwz 's proposal? More than likely that's what most ppl will want.

**Comment by NeQuissimus** [comment]
Oh hey, thanks for checking this out! And we can definitely include that update.
Would that be sufficient, @etspaceman?

**Comment by etspaceman** [comment]
Yeah that should be fine. Thanks!
