### ISSUE TITLE
Imports get added a semi-colon if code contains a semi-colon somewhere

### ISSUE THREAD

**Issue by slandelle** [NeQuissimus/sort-imports#71]
This is a regression introduced in 2.5.3.

ex:

```scala
import java.lang.Integer

class Foo {
  def bar(): Unit = { println("hello"); println("world")} // <= note the semicolon here 
}
```

gets formatted into:

```scala
import java.lang.Integer; // <== extra semicolon here

class Foo {
  def bar(): Unit = { println("hello"); println("world")}
}
```

**Comment by NeQuissimus** [comment]
yeah, this is unfortunate. I'll have a look some time this week unless somebody else wants to jump in

**Comment by slandelle** [comment]
Really no time on our side atm, sorry :(
In the meantime, we've removed the few occurrences of this pattern from our code.
