### ISSUE TITLE
`import` keyword missing in output

### ISSUE THREAD

**Issue by tuures** [NeQuissimus/sort-imports#9]
in:
```scala
import argonaut._, Argonaut._
import scala.util.Try

object Bug {
  def apply() = Try(Json.obj("foo" := "bar"))
}
```

out:
```scala
scala.util.Try

import import argonaut._, Argonaut._

object Bug {
  def apply() = Try(Json.obj("foo" := "bar"))
}

```

conf:
```js
SortImports.blocks = [
  "scala.",
  "*",
]
```

**Comment by tuures** [comment]
Sometimes the `import` keyword is also duplicated on the line with comma separated imports.

in:
```scala
import com.example.Foobar

import argonaut._, Argonaut._, com.example.MyJsonImplicits._
import scala.util.Try

object Bug extends Foobar {
  def apply() = Try(Json.obj("foo" := "bar").myExt[String])
}

```
out:
```scala
import scala.util.Try

com.example.Foobar
import import argonaut._, Argonaut._, com.example.MyJsonImplicits._

object Bug extends Foobar {
  def apply() = Try(Json.obj("foo" := "bar").myExt[String])
}
```

**Comment by NeQuissimus** [comment]
Oh, import lists... I assume this works just fine if you put each import on its own line?!

**Comment by tuures** [comment]
Yes, it works (syntax-wise at least) if each import is a separate import.

If you are curious, the imports are boilerplate so we like to keep them together in a consistent list which also avoids unused-import warnings if some import in the list is not used in some particular file.

**Comment by tuures** [comment]
I think I found the cause and a fix, will push a PR later
